"""initial_schema

Revision ID: d313d1bb189d
Revises: 
Create Date: 2026-05-11 22:23:41.962061

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd313d1bb189d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ref_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('drift_share', sa.Float(), nullable=False),
    sa.Column('triggered_retrain', sa.Boolean(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_version',
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('auroc', sa.Float(), nullable=True),
    sa.Column('auprc', sa.Float(), nullable=True),
    sa.Column('utility', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('patient',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('unit1', sa.Float(), nullable=True),
    sa.Column('unit2', sa.Float(), nullable=True),
    sa.Column('hosp_adm_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('sepsis_risk', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'hour', name='uq_prediction_patient_hour')
    )
    op.create_index('ix_prediction_patient_hour', 'prediction', ['patient_id', 'hour'], unique=False)
    op.create_table('vital',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Float(), nullable=True),
    sa.Column('o2sat', sa.Float(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('sbp', sa.Float(), nullable=True),
    sa.Column('map', sa.Float(), nullable=True),
    sa.Column('dbp', sa.Float(), nullable=True),
    sa.Column('resp', sa.Float(), nullable=True),
    sa.Column('etco2', sa.Float(), nullable=True),
    sa.Column('lab_values', sa.JSON(), nullable=True),
    sa.Column('sepsis_label', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'hour', name='uq_vital_patient_hour')
    )
    op.create_index('ix_vital_patient_hour', 'vital', ['patient_id', 'hour'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vital_patient_hour', table_name='vital')
    op.drop_table('vital')
    op.drop_index('ix_prediction_patient_hour', table_name='prediction')
    op.drop_table('prediction')
    op.drop_table('patient')
    op.drop_table('model_version')
    op.drop_table('drift_report')
    # ### end Alembic commands ###
